/** Reviewed public claims. Never derive product readiness from website releases. */
export const PUBLIC_EVIDENCE = {
  checkedOn: '2026-09-18',
  statusDate: '2026-09-14',
  tools: 'https://github.com/CopyPumpApp/CopyPump/blob/main/tools/README.md',
  architecture: 'https://github.com/CopyPumpApp/CopyPump/blob/main/docs/ARCHITECTURE.md',
  status: 'https://github.com/CopyPumpApp/CopyPump/blob/main/docs/PROJECT_STATUS.md',
  contributing: 'https://github.com/CopyPumpApp/CopyPump/blob/main/CONTRIBUTING.md',
  issues: 'https://github.com/CopyPumpApp/CopyPump/issues',
} as const
const en = {
  heroNote: 'Non-custodial autonomous trading on Solana, in development. The current focus is technical-alpha verification on Devnet.',
  benefits: ['Automatic wallet discovery', 'Execution within your rules', 'Your keys stay with you'],
  chapterDetails: [
    [['Discovery', 'The system analyses public trading history rather than asking you to assemble a copy list.'], ['Candidate', 'A detected wallet action becomes an observation to qualify, not an immediate order.']],
    [['Context', 'Freshness, liquidity and the quality of the candidate are checked before capital is committed.'], ['Rejection', 'A candidate that fails a required check should stop here—even when the source wallet has a strong history.']],
    [['Allocation', 'Capital and exposure limits define what the strategy may commit.'], ['Permission', 'An acceptable size never overrides slippage, authority or an emergency stop.']],
    [['Confirmation', 'Check the transaction outcome instead of treating submission as success.'], ['Reconciliation', 'Match positions and balances to the observed result; keep incomplete outcomes visible.']],
  ],
  control: {eyebrow:'AUTOMATION / RESPONSIBILITY', title:'Let the system find the activity.', accent:'Keep the decisions bounded.', intro:'CopyPump is being designed to separate intelligence from authority. Analysis can propose an action; the execution policy must still permit it.', system:'The system handles', user:'You define', systemItems:[['Discovery & analysis','Find candidate wallets and qualify their public activity.'],['Execution lifecycle','Prepare permitted actions, then confirm and reconcile the outcome.']], userItems:[['Strategy & risk','Choose the permitted strategy, capital limits, exposure and execution conditions.'],['Access & stop','Control wallet permissions and stop automation independently of the signal.']], ai:'AI can assist research and proposals. It is not intended to sign transactions or bypass deterministic policy checks.', detail:'Explore the product architecture'},
  evidence: {available:'OPEN TO INSPECTION', title:'There is more than a concept to inspect.', copy:'Public tools and documentation are available now. They make the verification work reviewable; they do not certify a working Mainnet trading service.', toolsTitle:'Run the public evidence validator', toolsCopy:'An offline utility checks the structure and safety boundaries of a proposed Devnet lifecycle manifest. No wallet or private repository access is required.', toolLimit:'A valid manifest is not proof that a transaction exists or that the trading lifecycle passed.', architectureTitle:'Review the architecture', architectureCopy:'Follow the separation between discovery, policy, wallet authority and reconciliation.', next:'CURRENT PROOF TARGET', nextCopy:'A reviewed Devnet cycle: buy → position → partial sell → full sell, with confirmation, balances and fee accounting.', source:'Read the dated public status'},
  projectOverview: {eyebrow:'THE SYSTEM BEHIND THE EXPERIENCE',title:'From discovery to a reviewable outcome.',copy:'This is the intended architecture of a technical-alpha product—not a list of production-certified features.',parts:[['Trading intelligence','Automatic wallet discovery, transaction analysis and candidate qualification. The system selects wallets; the user does not manually choose whom to copy.'],['Strategy and policy','Authoritative checks decide whether an action fits the user’s allocation, exposure, execution conditions and permissions.'],['Wallet and execution','User-controlled signing is separated from analysis. The target lifecycle covers buying, managing a position and partial or full exit.'],['Confirmation and audit','Reconcile the resulting position and balances, record fees, and preserve unresolved outcomes instead of reporting a false success.']],aiTitle:'AI assists. Policy stays authoritative.',aiCopy:'Research, classification, diagnostics and explanations can use AI. Signing, transaction submission, permission grants and risk overrides do not belong to the AI layer.',source:'Read the public architecture'},
  community: {copy:'Traders can shape the experience. Developers can run a public tool and choose a bounded task. Partners can discuss the project directly—without connecting a wallet.',contributor:'Start with a public tool or a focused issue, not access to the private trading engine.',issues:'Browse contributor tasks'},
  radar: {more:'More from this edition', note:'A reviewed first edition—not an automatic daily feed. Saved cases show an update only when a material revision is published.'},
}
const ru:typeof en = {
  heroNote:'Разрабатываем автономную торговлю на Solana без передачи ключей платформе. Сейчас — техническая альфа и проверки в Devnet.',
  benefits:['Автоматический поиск кошельков','Исполнение по вашим правилам','Ключи остаются у вас'],
  chapterDetails:[
    [['Поиск','Система анализирует публичную историю торговли. Собирать список кошельков для копирования вручную не нужно.'],['Кандидат','Обнаруженное действие становится наблюдением для проверки, а не немедленным ордером.']],
    [['Контекст','Свежесть, ликвидность и качество кандидата проверяются до обращения к капиталу.'],['Отказ','Не пройден обязательный критерий — кандидат останавливается, даже если у исходного кошелька сильная история.']],
    [['Капитал','Лимиты капитала и экспозиции задают допустимую нагрузку стратегии.'],['Разрешение','Подходящий размер не отменяет проверки проскальзывания, полномочий и экстренной остановки.']],
    [['Подтверждение','Проверяем исход транзакции: отправка ещё не означает успех.'],['Сверка','Сопоставляем позиции и балансы с фактическим результатом. Незавершённый исход должен оставаться видимым.']],
  ],
  control:{eyebrow:'АВТОМАТИЗАЦИЯ / ОТВЕТСТВЕННОСТЬ',title:'Система находит активность.',accent:'Вы задаёте границы.',intro:'В архитектуре CopyPump анализ отделён от полномочий. Система может предложить действие, но правила исполнения должны его разрешить.',system:'Задачи системы',user:'Решения пользователя',systemItems:[['Поиск и анализ','Обнаруживать кошельки-кандидаты и проверять их публичную активность.'],['Цикл исполнения','Подготовить допустимое действие, подтвердить и сверить результат.']],userItems:[['Стратегия и риск','Задать стратегию, лимиты капитала, экспозицию и условия исполнения.'],['Доступ и остановка','Контролировать разрешения кошелька и останавливать автоматизацию независимо от сигнала.']],ai:'AI помогает в исследованиях и подготовке предложений. Ему не отводятся подпись транзакций и обход обязательных проверок.',detail:'Подробнее об устройстве продукта'},
  evidence:{available:'МОЖНО ПРОВЕРИТЬ СЕЙЧАС',title:'Не только идея — материалы для проверки.',copy:'Публичные инструменты и документация уже доступны. Они позволяют изучить процесс проверки, но не подтверждают готовность торговли в Mainnet.',toolsTitle:'Запустить публичный валидатор',toolsCopy:'Автономная утилита проверяет структуру и границы безопасности манифеста цикла Devnet. Кошелёк и доступ к закрытому репозиторию не нужны.',toolLimit:'Корректный манифест не доказывает существование транзакций или прохождение торгового цикла.',architectureTitle:'Изучить архитектуру',architectureCopy:'Как разделены поиск, правила, полномочия кошелька и сверка результата.',next:'ТЕКУЩАЯ ЦЕЛЬ ПРОВЕРКИ',nextCopy:'Проверенный цикл Devnet: покупка → позиция → частичная продажа → полная продажа, с подтверждениями, балансами и учётом комиссий.',source:'Открыть датированный статус проекта'},
  projectOverview:{eyebrow:'КАК УСТРОЕН ПРОДУКТ',title:'От поиска до проверяемого результата.',copy:'Это задуманная архитектура продукта в технической альфе, а не перечень функций с доказанной production-готовностью.',parts:[['Торговая аналитика','Автоматическое обнаружение кошельков, анализ транзакций и отбор кандидатов. Кошельки выбирает система, а не пользователь вручную.'],['Стратегия и правила','Обязательные проверки определяют соответствие лимитам капитала, экспозиции, условиям исполнения и разрешениям пользователя.'],['Кошелёк и исполнение','Подпись под контролем пользователя отделена от анализа. Целевой цикл включает покупку, управление позицией, частичный и полный выход.'],['Подтверждение и история','Сверить итоговую позицию и балансы, учесть комиссии и сохранить незавершённые исходы вместо ложного отчёта об успехе.']],aiTitle:'AI помогает. Правила решают.',aiCopy:'Исследования, классификация, диагностика и объяснения могут использовать AI. Подпись, отправка транзакций, выдача разрешений и обход лимитов не относятся к его полномочиям.',source:'Читать публичную архитектуру'},
  community:{copy:'Трейдеры могут помочь с опытом использования. Разработчики — запустить открытый инструмент и взять ограниченную задачу. Партнёры — обсудить проект напрямую, без подключения кошелька.',contributor:'Начните с открытого инструмента или конкретной задачи, а не с доступа к закрытому торговому ядру.',issues:'Задачи для участников разработки'},
  radar:{more:'Ещё в этом выпуске',note:'Проверенный первый выпуск, не автоматическая ежедневная лента. Дополнения у сохранённых случаев появляются только после содержательной правки.'},
}
export const publicationCopy={en,ru}
