import { useCallback, useEffect, useLayoutEffect, useRef, useState, type MouseEvent, type ReactNode } from 'react'
import { createPortal } from 'react-dom'
import { useI18n } from '../i18n'
import { useMotion } from '../components/Experience'
import { Seo } from '../components/Seo'
import officialMark from '../imports/CopyPump_Official_Mark.webp'
import { navigateLocal } from '../lib/motion'
import { ART, CHANNELS, STATUS, premiumCopy } from './content'

const useCopy = () => { const { locale } = useI18n(); return premiumCopy[locale] }
function Arrow({ diagonal = false }: { diagonal?: boolean }) { return <svg className="arrow" width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d={diagonal?'M6 18 18 6M6 6h12v12':'M4 12h15m-6-6 6 6-6 6'} stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg> }
function Link({ to, children, className = '', onNavigate, ...rest }: {to:string;children:ReactNode;className?:string;onNavigate?:()=>void;[key:string]:unknown}) {
  const { pathFor } = useI18n()
  const click=(event:MouseEvent<HTMLAnchorElement>)=>{if(event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;event.preventDefault();onNavigate?.();navigateLocal(to)}
  return <a {...rest} href={pathFor(to)} onClick={click} className={className}>{children}</a>
}
function External({href,children,className=''}:{href:string;children:ReactNode;className?:string}){return <a href={href} className={className} {...(!href.startsWith('mailto:')?{target:'_blank',rel:'noopener noreferrer'}:{})}>{children}</a>}
function Mark({onNavigate}:{onNavigate?:()=>void}){const c=useCopy();return <Link to="/" className="brand" aria-label={`CopyPump — ${c.nav.home}`} onNavigate={onNavigate}><img src={officialMark} width="38" height="38" alt=""/><span>Copy<span>Pump</span></span></Link>}
function LocaleSwitch(){const {locale,setLocale}=useI18n();return <div className="locale-switch" role="group" aria-label={locale==='ru'?'Язык':'Language'}>{(['en','ru'] as const).map(l=><button type="button" key={l} aria-pressed={locale===l} onClick={()=>setLocale(l)}>{l.toUpperCase()}</button>)}</div>}
export function PremiumMotionToggle(){const m=useMotion(),c=useCopy().nav;return <button type="button" className="motion-toggle" onClick={m.toggle} aria-pressed={!m.paused&&!m.reduced} disabled={m.reduced} aria-label={m.reduced?c.reduced:m.paused?c.play:c.pause}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M3 12h3l3-7 5 14 3-7h4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg><span>{c.motion}</span><i/></button>}

export function PremiumHeader({simple=false}:{simple?:boolean}){
  const c=useCopy(),{setModal}=useMotion()
  const [open,setOpen]=useState(false)
  const trigger=useRef<HTMLButtonElement>(null),sheet=useRef<HTMLDivElement>(null),closeButton=useRef<HTMLButtonElement>(null)
  const restore=useRef(true)
  const close=useCallback(()=>setOpen(false),[])
  const destination=()=>{restore.current=false;close()}
  useLayoutEffect(()=>{
    if(!open)return
    const root=document.documentElement,body=document.body,app=document.getElementById('root')
    const before={root:root.style.overflow,body:body.style.overflow,inert:app?.inert??false,y:scrollY,path:location.pathname}
    setModal(true);root.classList.add('nav-open');root.style.overflow='hidden';body.style.overflow='hidden'
    closeButton.current?.focus({preventScroll:true});if(app)app.inert=true
    const keys=(e:KeyboardEvent)=>{
      if(e.key==='Escape'){e.preventDefault();close()}
      if(e.key!=='Tab')return
      const nodes=[...sheet.current!.querySelectorAll<HTMLElement>('a[href],button:not(:disabled)')].filter(x=>x.getClientRects().length>0)
      const first=nodes[0],last=nodes[nodes.length-1]
      if(e.shiftKey&&(document.activeElement===first||!sheet.current?.contains(document.activeElement))){e.preventDefault();last?.focus()}
      else if(!e.shiftKey&&(document.activeElement===last||!sheet.current?.contains(document.activeElement))){e.preventDefault();first?.focus()}
    }
    const focus=(e:FocusEvent)=>{if(!sheet.current?.contains(e.target as Node))closeButton.current?.focus({preventScroll:true})}
    const pop=()=>{if(location.pathname.replace(/^\/ru(?=\/|$)/,'')!==before.path.replace(/^\/ru(?=\/|$)/,'')){restore.current=false;close()}}
    document.addEventListener('keydown',keys);document.addEventListener('focusin',focus);window.addEventListener('popstate',pop)
    return()=>{
      document.removeEventListener('keydown',keys);document.removeEventListener('focusin',focus);window.removeEventListener('popstate',pop)
      if(app)app.inert=before.inert;root.style.overflow=before.root;body.style.overflow=before.body;root.classList.remove('nav-open');setModal(false)
      if(restore.current&&location.pathname===before.path){if(Math.abs(scrollY-before.y)>2)scrollTo({top:before.y,behavior:'auto'});trigger.current?.focus({preventScroll:true})}
    }
  },[open,close,setModal])
  useEffect(()=>{const fn=()=>close();addEventListener('pageshow',fn);return()=>removeEventListener('pageshow',fn)},[close])
  const items=[['/',c.nav.home],['/project',c.nav.product],['/progress',c.nav.progress],['/#community',c.nav.community],['/security',c.nav.security],['/contact',c.nav.contact]]
  return <><header className="site-header"><a className="skip-link" href="#main-content">{c.nav.skip}</a><div className="site-header__inner wrap"><Mark/><nav className="desktop-nav" aria-label={c.nav.label}><Link to="/project">{c.nav.product}</Link><Link to="/progress">{c.nav.progress}<i className="tiny-dot"/></Link>{!simple&&<Link to="/#community">{c.nav.community}</Link>}</nav><div className="header-actions"><LocaleSwitch/><PremiumMotionToggle/><button ref={trigger} type="button" className="menu-button" aria-label={c.nav.menu} aria-expanded={open} aria-haspopup="dialog" aria-controls="mobile-navigation" onClick={()=>{restore.current=true;setOpen(true)}}><span/><span/></button></div></div></header>
  {open&&createPortal(<div className="mobile-nav" id="mobile-navigation" role="dialog" aria-modal="true" aria-label={c.nav.label}><div className="mobile-nav__panel" ref={sheet}><div className="mobile-nav__top"><Mark onNavigate={destination}/><button ref={closeButton} type="button" className="icon-button" aria-label={c.nav.close} onClick={close}><span/><span/></button></div><div className="mobile-nav__body"><p className="eyebrow">{c.nav.explore}</p><nav>{items.map(([to,label],i)=><Link key={to} to={to} onNavigate={destination}><small>0{i+1}</small><strong>{label}</strong><Arrow diagonal/></Link>)}</nav></div><div className="mobile-nav__footer"><LocaleSwitch/><div className="mobile-nav__external"><External href={CHANNELS.github}>GitHub</External><External href={CHANNELS.discord}>Discord</External><External href={CHANNELS.x}>X</External></div><PremiumMotionToggle/></div></div></div>,document.body)}
  </>
}
export function PremiumFooter(){const c=useCopy();return <footer className="site-footer wrap"><div className="footer-brand"><Mark/><p>{c.footer.line}</p><small>© 2026 CopyPump</small></div><div className="footer-links"><nav aria-label="CopyPump"><External href={CHANNELS.x}>X <Arrow diagonal/></External><External href={CHANNELS.discord}>Discord <Arrow diagonal/></External><External href={CHANNELS.github}>GitHub <Arrow diagonal/></External><External href={CHANNELS.email}>Email <Arrow diagonal/></External></nav><nav aria-label="Legal"><Link to="/privacy">{c.footer.privacy}</Link><Link to="/terms">{c.footer.terms}</Link><Link to="/security">{c.footer.security}</Link><Link to="/contact">{c.footer.contact}</Link></nav><p>{c.footer.disclaimer}</p></div></footer>}
function Layout({children,title,description,path}:{children:ReactNode;title:string;description:string;path:string}){return <div className="app-shell premium-v48" data-release="48.0-premium"><Seo title={title} description={description} path={path}/><PremiumHeader/><main id="main-content" tabIndex={-1}>{children}</main><PremiumFooter/></div>}
function DateLabel(){const {locale}=useI18n();return <time dateTime={STATUS.sourceDate}>{new Intl.DateTimeFormat(locale==='ru'?'ru-RU':'en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(`${STATUS.sourceDate}T12:00:00Z`))}</time>}
function StatusBadge(){const c=useCopy();return <Link to="/progress" className="status-badge"><i/>{c.hero.label}<Arrow diagonal/></Link>}

function ProductExperience(){
  const c=useCopy().experience,m=useMotion()
  const [active,setActive]=useState(0),[limit,setLimit]=useState(0.35),[inView,setInView]=useState(false)
  const root=useRef<HTMLDivElement>(null),buttons=useRef<(HTMLButtonElement|null)[]>([])
  useEffect(()=>{if(!root.current||!('IntersectionObserver'in window))return;const io=new IntersectionObserver(([e])=>setInView(e.isIntersecting));io.observe(root.current);return()=>io.disconnect()},[])
  const chapter=c.chapters[active],name=ART.objects[active],allowed=limit>=0.5
  return <section className="experience wrap section-space" id="experience" aria-labelledby="experience-title"><div className="section-heading" data-reveal><div><p className="eyebrow">01 / {c.eyebrow}</p><h2 id="experience-title">{c.title}<br/><span>{c.accent}</span></h2></div><p>{c.intro}</p></div><div className="experience-tabs" role="tablist" aria-label={c.eyebrow}>{c.chapters.map((s,i)=><button key={i} type="button" role="tab" id={`chapter-${i}`} aria-controls="experience-panel" aria-selected={active===i} tabIndex={active===i?0:-1} ref={el=>{buttons.current[i]=el}} onClick={()=>setActive(i)} onKeyDown={e=>{let next=i;if(e.key==='ArrowRight')next=(i+1)%4;else if(e.key==='ArrowLeft')next=(i+3)%4;else if(e.key==='Home')next=0;else if(e.key==='End')next=3;else return;e.preventDefault();setActive(next);buttons.current[next]?.focus()}}><span>0{i+1}</span>{s.name}<i/></button>)}</div>
    <div className="experience-stage" ref={root} id="experience-panel" role="tabpanel" aria-labelledby={`chapter-${active}`} tabIndex={0} data-ambient={m.running&&inView?'on':'off'}>
      <div className="experience-art"><div className="art-orbit" aria-hidden="true"/><picture key={name}><source media="(max-width:600px)" srcSet={`/media/v48/${name}-480.webp`}/><img src={`/media/v48/${name}-800.webp`} width="800" height="1019" decoding="async" loading="lazy" alt=""/></picture><span className="art-coordinate" aria-hidden="true">CP / 0{active+1}</span></div>
      <div className="experience-story" key={active}><p className="eyebrow">{chapter.key}</p><h3>{chapter.title}</h3><p>{chapter.copy}</p><div className="instrument"><div className="instrument-heading"><i className="tiny-dot"/><span>{c.example}</span><svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden="true"><rect x="5" y="10" width="14" height="10" rx="2" stroke="currentColor"/><path d="M8 10V7a4 4 0 0 1 8 0v3" stroke="currentColor"/></svg></div>{active===2?<><div className="policy-readout"><span>{c.test}</span><b>0.50 <small>SOL</small></b></div><label className="policy-range" htmlFor="capital-limit"><span>{c.limit}</span><output htmlFor="capital-limit">{limit.toFixed(2)} SOL</output><input id="capital-limit" type="range" min="0.1" max="1" step="0.05" value={limit} onChange={e=>setLimit(Number(e.target.value))}/><small>0.10 SOL</small><small>1.00 SOL</small></label><div className={`policy-result ${allowed?'allowed':'blocked'}`} role="status" aria-live="polite"><strong><i/>{allowed?c.allowed:c.blocked}</strong><p>{allowed?c.allowedNote:c.blockedNote}</p></div></>:<dl className="signal-record">{chapter.rows.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>}</div><Link to="/project" className="text-link">{active===2?c.policyLink:c.detail}<Arrow/></Link></div>
    </div></section>
}
export function PremiumLanding(){const c=useCopy();return <Layout title="CopyPump — Smart money. Your rules." description={c.hero.intro} path="/">
  <section className="hero" aria-labelledby="hero-title"><div className="hero-art" aria-hidden="true"><picture><source media="(max-width:760px)" srcSet={ART.backgroundSmall}/><img src={ART.background} width="1600" height="900" fetchPriority="high" decoding="async" alt=""/></picture></div><div className="hero-content wrap"><div className="hero-topline"><p className="eyebrow">{c.hero.eyebrow}</p><StatusBadge/></div><div className="hero-type"><h1 id="hero-title">{c.hero.line1}<br/><span>{c.hero.line2}</span></h1><p className="hero-intro">{c.hero.intro}</p><div className="hero-actions"><Link to="/#experience" className="button button-primary">{c.hero.primary}<Arrow/></Link><Link to="/progress" className="text-link">{c.hero.secondary}<Arrow diagonal/></Link></div></div><div className="hero-bottom"><span className="hero-signature">{c.hero.stamp}</span><p>{c.hero.bottom}</p><span className="hero-discover" aria-hidden="true">↓</span></div></div></section>
  <ProductExperience/>
  <section className="status-section wrap section-space" id="status" aria-labelledby="status-title"><div className="status-copy" data-reveal><p className="eyebrow">02 / {c.status.eyebrow}</p><h2 id="status-title">{c.status.title}<br/><span>{c.status.accent}</span></h2><p>{c.status.intro}</p><Link to="/progress" className="text-link">{c.status.link}<Arrow/></Link></div><div className="status-card" data-reveal><div className="status-card-top"><p className="eyebrow">{c.status.label}</p><i className="status-beacon"/></div><h3>{c.status.now}</h3><dl><div><dt>{c.status.network}</dt><dd>Solana Devnet</dd></div><div><dt>{c.status.mainnet}</dt><dd className="locked-label">{c.status.locked}</dd></div></dl><p className="status-source">{c.status.source} <DateLabel/></p><p className="fine-print">{c.status.note}</p></div></section>
  <section className="community wrap section-space" id="community" aria-labelledby="community-title"><div data-reveal><p className="eyebrow">03 / {c.cta.eyebrow}</p><h2 id="community-title">{c.cta.title}</h2><p>{c.cta.copy}</p><div className="community-actions"><External href={CHANNELS.discord} className="button button-primary">{c.cta.community}<Arrow diagonal/></External><External href={CHANNELS.github} className="text-link">{c.cta.builder}<Arrow diagonal/></External></div><External href={CHANNELS.email} className="partner-link">{c.cta.partners} ↗</External></div><div className="community-monogram" aria-hidden="true">CP<span>SOFTWARE. WITH INTENT.</span></div></section>
  </Layout>}

export function PremiumProject(){const c=useCopy(),[tab,setTab]=useState(0),tabs=useRef<(HTMLButtonElement|null)[]>([]);return <Layout title={`${c.nav.product} — CopyPump`} description={c.product.intro} path="/project"><section className="document-hero wrap"><p className="eyebrow">{c.product.eyebrow}</p><h1>{c.product.title}<br/><span>{c.product.accent}</span></h1><p>{c.product.intro}</p></section><section className="product-document wrap" aria-label={c.nav.product}><div className="document-tabs" role="tablist" aria-label={c.nav.product}>{c.product.tabs.map((label,i)=><button key={label} ref={el=>{tabs.current[i]=el}} type="button" role="tab" id={`product-tab-${i}`} aria-selected={tab===i} aria-controls="product-panel" tabIndex={tab===i?0:-1} onClick={()=>setTab(i)} onKeyDown={e=>{let n=i;if(e.key==='ArrowRight')n=(i+1)%3;else if(e.key==='ArrowLeft')n=(i+2)%3;else if(e.key==='Home')n=0;else if(e.key==='End')n=2;else return;e.preventDefault();setTab(n);tabs.current[n]?.focus()}}>{label}</button>)}</div><div role="tabpanel" id="product-panel" aria-labelledby={`product-tab-${tab}`} tabIndex={0} className="document-panel">
    {tab===0?<><header><h2>{c.product.policyTitle}</h2><p>{c.product.policyIntro}</p></header><div className="control-grid">{c.product.controls.map((x,i)=><article key={x.name}><div className="control-label"><span>0{i+1}</span><p className="eyebrow">{x.tag}</p></div><h3>{x.name}</h3><p>{x.detail}</p></article>)}</div></>:tab===1?<><header><h2>{c.product.authorityTitle}</h2><p>{c.product.authorityIntro}</p></header><div className="authority-records">{c.product.authority.map((x,i)=><article key={x.title}><span className="record-number">0{i+1}</span><div><h3>{x.title}</h3><p>{x.copy}</p></div></article>)}</div></>:<><header><h2>{c.product.faqTitle}</h2></header><div className="faq-list">{c.product.faq.map(x=><details className="faq-item" key={x.q}><summary>{x.q}<span aria-hidden="true">+</span></summary><p>{x.a}</p></details>)}</div></>}
    <Link to="/progress" className="text-link document-source">{c.product.evidence}<Arrow/></Link></div></section></Layout>}

export function PremiumProgress(){const c=useCopy();return <Layout title={`${c.nav.progress} — CopyPump`} description={c.progress.intro} path="/progress"><section className="document-hero wrap"><p className="eyebrow">{c.progress.eyebrow}</p><h1>{c.progress.title}<br/><span>{c.progress.accent}</span></h1><p>{c.progress.intro}</p><p className="dated-source">{c.progress.date} <DateLabel/></p></section><section className="progress-overview wrap" aria-labelledby="progress-stage"><div className="progress-stage" data-reveal><span className="eyebrow">SOLANA / DEVNET</span><h2 id="progress-stage">{c.progress.summaryTitle}</h2><p>{c.progress.summaryCopy}</p><span className="stage-orb" aria-hidden="true"/></div><div className="progress-gates" data-reveal>{c.progress.gates.map(x=><article key={x.name}><div><h3>{x.name}</h3><span className={`gate-tag ${x.tone}`}><i/>{x.state}</span></div><p>{x.copy}</p></article>)}</div></section><section className="milestone-section wrap section-space"><div data-reveal><p className="eyebrow">{c.progress.currentLabel}</p><h2>{c.progress.currentTitle}</h2><p>{c.progress.currentCopy}</p></div><details className="engineering-note"><summary>{c.progress.noteTitle}<span>+</span></summary><p>{c.progress.note}</p></details></section><section className="roadmap-section wrap section-space" id="roadmap"><div data-reveal><p className="eyebrow">{c.progress.roadmapLabel}</p><h2>{c.progress.roadmapTitle}</h2></div><ol>{c.progress.roadmap.map((x,i)=><li key={x.title} data-reveal><span>0{i+1}</span><h3>{x.title}</h3><p>{x.copy}</p></li>)}</ol><div className="source-record"><External href={STATUS.source} className="text-link">{c.progress.source}<Arrow diagonal/></External><p>{c.progress.update}</p></div></section></Layout>}
