import { useState } from 'react'
import { Header } from '../components/Header'
import { SiteFooter } from '../components/SiteFooter'
import { Seo } from '../components/Seo'
import { useI18n } from '../i18n'
import { useSystem } from '../hooks/useSystem'
import { ProjectRail } from '../components/ProjectRails'
import { ProductStory } from '../components/ProductStory'
import { HeroScene, workflowObjects } from '../components/HeroScene'
import { ServiceLogo } from '../components/ServiceLogo'
import { Atmosphere } from '../components/Experience'
import { navigateLocal, smoothScrollToId } from '../lib/motion'
import { evaluateExample } from '../lib/decision'

const source='https://github.com/CopyPumpApp/CopyPump/blob/main/docs/'
const workflowAsset=(name:string)=>`/workflow-objects/${name}.webp?v=20260916-light`

function DecisionExample(){
  const{dict,locale}=useI18n(),c=dict.studio.demo
  const[limit,setLimit]=useState(.35),[age,setAge]=useState(12),[stopped,setStopped]=useState(false)
  const amount=.5,result=evaluateExample({amount,limit,age,stopped})
  const format=(v:number)=>v.toLocaleString(locale,{minimumFractionDigits:2,maximumFractionDigits:2})
  const statuses=[true,result.fresh,result.capital&&!stopped,result.allowed]
  const reason=result.reason==='stop'?c.stopReason:result.reason==='age'?c.ageReason:result.reason==='limit'?c.limitReason:c.allowReason
  return <section id="decision-demo" className="decision-section" aria-labelledby="decision-title" tabIndex={-1} data-motion-scene>
    <div className="section-shell">
      <div className="section-intro" data-reveal="0" data-reveal-kind="title"><span className="eyebrow">{c.eyebrow}</span><div><h2 id="decision-title">{c.title}</h2><p>{c.intro}</p></div></div>
      <div className="workflow-scene" aria-label={c.trace} data-pinned-story>{workflowObjects.map((name,i)=><div className={`workflow-node ${statuses[i]?'passed':'stopped'}`} key={name} data-reveal={String(i*70)}><div className="workflow-image"><img src={workflowAsset(name)} width="440" height="560" loading="lazy" decoding="async" alt=""/></div><div className="workflow-caption"><span>{String(i+1).padStart(2,'0')}</span><h3>{c.steps[i]}</h3><i aria-hidden="true"/></div><p>{c.stepNotes[i]}</p></div>)}</div>
      <div className="decision-desk" data-reveal="160"><div className="decision-controls" data-tilt><div className="example-amount"><span>{c.amount}</span><strong>{format(amount)} <small>SOL</small></strong></div><label className="range-control" htmlFor="capital-limit"><span>{c.limit}</span><output htmlFor="capital-limit">{format(limit)} SOL</output><input id="capital-limit" type="range" min="0.1" max="1" step="0.05" value={limit} onChange={e=>setLimit(Number(e.target.value))}/><small>0.10 SOL</small><small>1.00 SOL</small></label><label className="range-control" htmlFor="signal-age"><span>{c.age}</span><output htmlFor="signal-age">{age} {c.ageUnit}</output><input id="signal-age" type="range" min="5" max="90" step="1" value={age} onChange={e=>setAge(Number(e.target.value))}/><small>5 {c.ageUnit}</small><small>90 {c.ageUnit}</small></label><label className="stop-control"><span><strong>{c.stop}</strong></span><input type="checkbox" checked={stopped} onChange={e=>setStopped(e.target.checked)}/><span className="toggle" aria-hidden="true"/></label><button className="text-link" onClick={()=>{setLimit(.35);setAge(12);setStopped(false)}}>{c.reset}</button></div><div className={`decision-outcome ${result.allowed?'is-allowed':'is-blocked'}`} data-tilt><div className="outcome-heading"><span className="eyebrow">{c.statusLabel}</span><span className="status-dot" aria-hidden="true"/></div><div role="status" aria-live="polite"><h3>{result.allowed?c.allowed:c.blocked}</h3><p>{reason}</p></div><dl className="decision-trace"><div><dt>{c.fresh}</dt><dd>{result.fresh?c.pass:c.fail}</dd></div><div><dt>{c.capital}</dt><dd>{result.capital?c.pass:c.fail}</dd></div><div><dt>{c.authority}</dt><dd>{stopped?c.paused:c.pass}</dd></div></dl><small>{c.notTrade}</small></div></div>
      <p className="demo-disclaimer"><span aria-hidden="true">◌</span>{c.disclaimer}</p>
    </div>
  </section>
}

export function LandingPage(){
  const{dict,locale}=useI18n(),c=dict.studio,v=dict.cinema,{data,loading,error,retry}=useSystem()
  const explore=()=>{smoothScrollToId('decision-demo');document.getElementById('decision-demo')?.focus({preventScroll:true})}
  const journalEntries=[[c.journal.currentLabel,c.journal.currentTitle,c.journal.currentText],[c.journal.nextLabel,c.journal.nextTitle,c.journal.nextText],[c.journal.lockedLabel,c.journal.lockedTitle,c.journal.lockedText]]
  return <div className="app-shell cinematic-v47" data-release="47.9-recovery"><Seo title={dict.landing.seo.title} description={dict.landing.seo.description}/><Header/><div className="site-scroll-background" aria-hidden="true"/><Atmosphere/><main id="main-content">
    <section className="hero" id="product" aria-labelledby="hero-title" data-motion-scene><div className="section-shell hero-shell"><div className="hero-kicker"><span className="eyebrow"><i/>{v.hero.eyebrow}</span><span className="stage">{c.hero.stage}</span></div><div className="hero-composition"><div className="hero-type" data-reveal="0" data-reveal-kind="title"><h1 id="hero-title"><span>{v.hero.lead}</span><span className="hero-focus">{v.hero.focus}</span><span className="hero-ending">{v.hero.end}</span></h1><p className="hero-description">{v.hero.intro}</p><div className="hero-actions"><button className="button button--primary" onClick={explore}>{v.hero.primary}</button><button className="text-link" onClick={()=>navigateLocal('/project')}>{locale==='ru'?'О проекте':'Project'}</button></div><div className="hero-trust"><span><i/> {c.boundary.labels[0]}</span><span><i/> {c.boundary.labels[1]}</span><span><i/> {c.boundary.labels[2]}</span></div></div><HeroScene/></div></div></section>
    <section id="why-copypump" className="problem-section section-shell" aria-labelledby="problem-title"><div className="problem-heading" data-reveal="0" data-reveal-kind="title"><span className="eyebrow">01 / {v.problem.eyebrow}</span><h2 id="problem-title">{v.problem.title}<br/><em>{v.problem.accent}</em></h2><p>{v.problem.intro}</p></div><div className="problem-comparison"><div className="comparison-labels"><span/><span>{v.problem.before}</span><span>{v.problem.after}</span></div>{v.problem.rows.map((row,i)=><article className="problem-row" key={row.title} data-reveal={String(i*70)}><div><span className="problem-index">{String(i+1).padStart(2,'0')}</span><h3>{row.title}</h3></div><p><span className="mobile-label">{v.problem.before}</span>{row.before}</p><p className="problem-answer"><span className="mobile-label">{v.problem.after}</span>{row.after}</p></article>)}</div><div className="problem-bottom" data-reveal="160"><div><strong>{v.problem.for}</strong><p className="fine-print">{v.problem.note}</p></div><button className="text-link" onClick={explore}>{v.problem.cta}</button></div></section>
    <ProductStory/>
    <DecisionExample/>
    <section id="authority" className="authority-section section-shell" aria-labelledby="authority-title"><div className="authority-top" data-reveal="0" data-reveal-kind="title"><div><span className="eyebrow">{c.boundary.eyebrow}</span><h2 id="authority-title">{c.boundary.title}<br/><em>{c.boundary.accent}</em></h2></div><p>{c.boundary.intro}</p></div><div className="authority-columns">{c.boundary.labels.map((label,i)=><article key={label} data-reveal={String(i*90)} data-tilt><span className="column-index">{String(i+1).padStart(2,'0')} /</span><h3>{label}</h3><p>{c.boundary.texts[i]}</p></article>)}</div><div className="authority-bottom" data-reveal="190"><div><p className="fine-print">{c.boundary.note}</p><a className="text-link" href={`${source}SECURITY_MODEL.md`} target="_blank" rel="noopener noreferrer">{c.boundary.more}</a></div><div>{c.boundary.details.map(item=><details className="text-detail" key={item.q}><summary>{item.q}<span>+</span></summary><p>{item.a}</p></details>)}</div></div></section>
    <ProjectRail variant="journey"/>
    <section id="journal" className="journal-section" aria-labelledby="journal-title"><div className="section-shell journal-layout"><div className="journal-heading" data-reveal="0" data-reveal-kind="title"><span className="eyebrow">{c.journal.eyebrow}</span><h2 id="journal-title">{c.journal.title}<br/><em>{c.journal.accent}</em></h2><p>{c.journal.intro}</p><a className="text-link" href={`${source}PROJECT_STATUS.md`} target="_blank" rel="noopener noreferrer">{c.journal.source}</a><div className="journal-date"><time dateTime={c.journal.dateIso}>{c.journal.date}</time><small>{c.journal.dated}</small></div></div><div className="journal-entries">{journalEntries.map(([label,title,copy],i)=><article key={label} data-reveal={String(i*90)}><span className={`journal-dot dot-${i}`} aria-hidden="true"/><span className="eyebrow">{label}</span><h3>{title}</h3><p>{copy}</p></article>)}<nav className="journal-sources"><a href={`${source}ROADMAP.md`} target="_blank" rel="noopener noreferrer">{c.journal.roadmap}</a><a href={`${source}ARCHITECTURE.md`} target="_blank" rel="noopener noreferrer">{c.journal.architecture}</a></nav></div><div className="api-status" data-reveal="190"><span><i className={!loading&&!error&&data?'is-online':''}/>{c.journal.api}: <strong>{loading?c.journal.loading:error?c.journal.offline:c.journal.online}</strong></span><small>{c.journal.apiNote}</small><button className="text-link" onClick={retry} disabled={loading}>{c.journal.retry}</button></div></div></section>
    <ProjectRail variant="roadmap"/>
    <section id="community" className="community-section section-shell" data-motion-scene><div className="cp-invitation"><div className="cp-invitation-copy" data-reveal="0" data-reveal-kind="title"><span className="eyebrow">{c.community.eyebrow}</span><h2>{c.community.title}<br/><em>{c.community.accent}</em></h2><p>{c.community.description}</p></div><div className="project-availability" data-reveal="90"><h3>{dict.explore.brief.title}</h3><p>{dict.explore.brief.text}</p></div></div><div className="community-bottom" data-reveal="160"><p>{c.community.footer}</p><nav><a href="https://x.com/CopyPumpAI" target="_blank" rel="noopener noreferrer"><ServiceLogo name="x" size={22}/>{c.community.x}</a><a href="https://discord.gg/WS95eXrGB" target="_blank" rel="noopener noreferrer"><ServiceLogo name="discord"/>{c.community.discord}</a><a href="https://github.com/CopyPumpApp/CopyPump" target="_blank" rel="noopener noreferrer"><ServiceLogo name="github"/>{c.community.github}</a><a href="mailto:copypumphq@gmail.com"><span className="mail-icon">@</span>{c.community.email}</a></nav></div></section>
  </main><SiteFooter/></div>
}
