import { createContext, useContext, useEffect, useLayoutEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import { useI18n } from '../i18n'
const MotionContext=createContext({running:false,paused:false,reduced:false,modal:false,toggle:()=>{}})
export const useMotion=()=>useContext(MotionContext)
export function Experience({children,routeKey}:{children:ReactNode;routeKey:string}){
 const[paused,setPaused]=useState(false),[reduced,setReduced]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches),[visible,setVisible]=useState(!document.hidden),[modal,setModal]=useState(false)
 const running=!paused&&!reduced&&visible&&!modal,active=useRef(new Set<Animation>())
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)'),change=()=>setReduced(media.matches),visibility=()=>setVisible(!document.hidden),overlay=()=>setModal(Boolean(document.querySelector('.mobile-nav,[role="dialog"][aria-modal="true"]'))),observer=new MutationObserver(overlay);observer.observe(document.body,{subtree:true,childList:true});overlay();media.addEventListener('change',change);document.addEventListener('visibilitychange',visibility);return()=>{observer.disconnect();media.removeEventListener('change',change);document.removeEventListener('visibilitychange',visibility)}},[])
 useEffect(()=>{document.documentElement.dataset.motion=running?'on':'off';if(!running){active.current.forEach(a=>a.cancel());active.current.clear();document.querySelectorAll<HTMLElement>('[data-reveal]').forEach(n=>{n.style.opacity='1';n.style.transform='none';n.style.willChange=''})}return()=>{delete document.documentElement.dataset.motion}},[running])
 useLayoutEffect(()=>{const nodes=[...document.querySelectorAll<HTMLElement>('[data-reveal]')];if(!nodes.length)return;const show=(n:HTMLElement)=>{n.style.opacity='1';n.style.transform='none';n.style.willChange='';n.dataset.revealed='true'};if(paused||reduced||!('IntersectionObserver'in window)){nodes.forEach(show);return}const hide=(n:HTMLElement)=>{n.style.opacity='0';n.style.transform=n.dataset.revealKind==='title'?'translate3d(0,20px,0)':'translate3d(0,14px,0)';n.style.willChange='opacity, transform';n.dataset.revealed='false'};nodes.forEach(n=>{const r=n.getBoundingClientRect();r.top>innerHeight*.94?hide(n):show(n)});const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(!entry.isIntersecting)return;const n=entry.target as HTMLElement;if(n.dataset.revealed==='true'){observer.unobserve(n);return}const raw=Number(n.dataset.reveal||0),delay=Number.isFinite(raw)?Math.min(140,Math.max(0,raw)):0;if(typeof n.animate!=='function'){show(n);observer.unobserve(n);return}const a=n.animate([{opacity:0,transform:n.style.transform},{opacity:1,transform:'translate3d(0,0,0)'}],{duration:n.dataset.revealKind==='title'?560:440,delay,easing:'cubic-bezier(.22,1,.36,1)',fill:'forwards'});active.current.add(a);a.finished.then(()=>{active.current.delete(a);show(n);observer.unobserve(n)},()=>active.current.delete(a))})},{threshold:.06,rootMargin:'0px 0px -4% 0px'});nodes.forEach(n=>{if(n.dataset.revealed!=='true')observer.observe(n)});return()=>{observer.disconnect();active.current.forEach(a=>a.cancel());active.current.clear();nodes.forEach(n=>{n.style.opacity='';n.style.transform='';n.style.willChange='';delete n.dataset.revealed})}},[routeKey,paused,reduced])
 useEffect(()=>{if(!running||reduced||innerWidth<1000||!matchMedia('(pointer:fine)').matches)return;const hero=document.querySelector<HTMLElement>('.hero');if(!hero)return;let raf=0,mx=0,my=0;const draw=()=>{raf=0;hero.style.setProperty('--pointer-x-small',`${(mx*4).toFixed(2)}px`);hero.style.setProperty('--pointer-y-small',`${(my*3).toFixed(2)}px`)};const pointer=(e:PointerEvent)=>{mx=(e.clientX/innerWidth-.5)*2;my=(e.clientY/innerHeight-.5)*2;if(!raf)raf=requestAnimationFrame(draw)};addEventListener('pointermove',pointer,{passive:true});return()=>{if(raf)cancelAnimationFrame(raf);removeEventListener('pointermove',pointer);hero.style.removeProperty('--pointer-x-small');hero.style.removeProperty('--pointer-y-small')}},[running,reduced,routeKey])
 const value=useMemo(()=>({running,paused,reduced,modal,toggle:()=>setPaused(old=>!old)}),[running,paused,reduced,modal]);return <MotionContext.Provider value={value}>{children}<CopyGuard/></MotionContext.Provider>
}
export function MotionToggle(){const{dict}=useI18n(),c=dict.cinema.motion,motion=useMotion();return <button className="motion-toggle" onClick={motion.toggle} disabled={motion.reduced} aria-pressed={!motion.paused&&!motion.reduced} aria-label={motion.reduced?c.reduced:motion.paused?c.play:c.pause} title={motion.reduced?c.reduced:motion.paused?c.play:c.pause}><svg viewBox="0 0 24 24" width="18" height="18" aria-hidden="true"><path d="M3 12h2l3-7 4 14 4-12 3 5h2" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/></svg><span>{c.label}</span><i aria-hidden="true"/></button>}
const COPY_ALLOWED='input,textarea,[contenteditable="true"],[data-copy-allowed],code,pre,.legal-main,.notice,.wallet-help,a[href^="mailto:"]';function elementOf(node:Node|null):Element|null{return node instanceof Element?node:node?.parentElement||null}export function copySelectionAllowed(selection:Selection|null):boolean{if(!selection||selection.isCollapsed)return false;const start=elementOf(selection.anchorNode)?.closest(COPY_ALLOWED);return!!start&&start.contains(selection.focusNode)}
function CopyGuard(){const{dict}=useI18n(),[notice,setNotice]=useState(false),timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);useEffect(()=>{const allowTarget=(e:Event)=>elementOf(e.target as Node)?.closest(COPY_ALLOWED),notify=()=>{setNotice(true);clearTimeout(timer.current);timer.current=setTimeout(()=>setNotice(false),2800)},copy=(e:ClipboardEvent)=>{if(elementOf(e.target as Node)?.closest('input,textarea,[contenteditable="true"]'))return;if(copySelectionAllowed(getSelection()))return;if(allowTarget(e)&&!getSelection()?.toString())return;if(!document.querySelector('.app-shell'))return;e.preventDefault();e.clipboardData?.setData('text/plain','');notify()},context=(e:MouseEvent)=>{if(allowTarget(e)||elementOf(e.target as Node)?.closest('a,button,summary'))return;if(elementOf(e.target as Node)?.closest('.app-shell')){e.preventDefault();notify()}};document.addEventListener('copy',copy);document.addEventListener('contextmenu',context);return()=>{document.removeEventListener('copy',copy);document.removeEventListener('contextmenu',context);clearTimeout(timer.current)}},[]);return <div className={`copy-notice ${notice?'visible':''}`} role="status" aria-live="polite">{notice?dict.cinema.guard.notice:''}</div>}
export function Atmosphere(){return <div className="cinematic-atmosphere" aria-hidden="true"><i/><i/><div/></div>}
