import { useI18n } from '../i18n'

type Detail={k:string;title:string;lead:string;body:string;points:string[]}
export function ProjectDetails(){
 const{locale}=useI18n(),ru=locale==='ru'
 const items:Detail[]=ru?[
  {k:'smart',title:'Как CopyPump читает smart money',lead:'Мы не превращаем каждое движение выбранного кошелька в сделку.',body:'Публичная активность выбранных кошельков сначала становится кандидатом. Затем CopyPump должен проверить свежесть сигнала, качество рынка и правила пользователя. Только после этого кандидат вообще может приблизиться к исполнению.',points:['Наблюдение за выбранными публичными кошельками','Нормализация сигнала и отсечение шума','Слабый или устаревший сигнал может быть отклонён до использования капитала']},
  {k:'filter',title:'Почему это не слепой copy trading',lead:'Прибыльный кошелёк не означает, что стоит копировать каждую его транзакцию.',body:'Важна не только личность источника. Имеют значение момент входа, ликвидность, проскальзывание, размер позиции и то, соответствует ли действие вашим ограничениям.',points:['Сигнал — это кандидат, а не команда','Правила риска имеют приоритет над рекомендацией','Отказ — нормальный результат, если условия не подходят']},
  {k:'control',title:'Что контролирует пользователь',lead:'Автоматизация должна работать внутри заданного вами контура.',body:'Архитектура CopyPump строится вокруг ограниченных полномочий. Подключение кошелька само по себе не должно означать безграничный доступ к активам.',points:['Лимит капитала и размер действия','Проскальзывание и экспозиция','Отзывные полномочия и аварийная остановка','Phantom — текущий утверждённый браузерный кошелёк']},
  {k:'fail',title:'Что происходит, если проверка не пройдена',lead:'Система должна остановиться или показать несверенное состояние — не притворяться, что всё успешно.',body:'Если сигнал устарел, превышен лимит или полномочия отозваны, действие блокируется. Если исполнение не подтверждено, результат должен оставаться несверенным до получения доказательств.',points:['Stale signal → BLOCK','Capital/risk limit exceeded → BLOCK','Authority revoked → STOP','Execution not reconciled → не показывать ложный SUCCESS']},
  {k:'status',title:'Где проект находится сейчас',lead:'Devnet first. Proof first. Mainnet не открыт.',body:'Каноническая среда разработки — реальные тестовые транзакции Solana Devnet. Последний сохранённый полный тестовый прогон ещё содержал незакрытые проверки, поэтому сайт не должен выдавать продукт за готовый к Mainnet. Переход к Mainnet дополнительно требует явного решения человека.',points:['TESTNET = Solana Devnet','Последний сохранённый full-suite: 994 PASS / 61 FAIL / 1 SKIP','Готовность требует двух последовательных чистых verification passes без новых P0/P1','Mainnet execution жёстко заблокирован до явного human approval']}
 ]:[
  {k:'smart',title:'How CopyPump reads smart money',lead:'We do not turn every move from a selected wallet into a trade.',body:'Public activity from selected wallets first becomes a candidate. CopyPump then has to evaluate signal freshness, market quality and the user’s rules. Only then can a candidate move closer to execution.',points:['Observe selected public wallets','Normalize signals and filter noise','Weak or stale signals can be rejected before capital is considered']},
  {k:'filter',title:'Why this is not blind copy trading',lead:'A profitable wallet does not make every transaction worth copying.',body:'The source alone is not enough. Entry timing, liquidity, slippage, position size and your own limits all matter before an action should be allowed.',points:['A signal is a candidate, not a command','Risk rules outrank a recommendation','A rejection is a valid outcome when conditions do not fit']},
  {k:'control',title:'What the user controls',lead:'Automation is intended to operate inside an envelope you define.',body:'CopyPump is designed around bounded authority. Connecting a wallet should not equal unlimited access to assets.',points:['Capital ceiling and action size','Slippage and exposure','Revocable authority and emergency stop','Phantom is the currently approved browser wallet']},
  {k:'fail',title:'What happens when a check fails',lead:'The system should stop or expose an unreconciled state — not pretend everything succeeded.',body:'A stale signal, exceeded limit or revoked authority blocks the action. If execution cannot be confirmed, the outcome should remain unreconciled until evidence exists.',points:['Stale signal → BLOCK','Capital/risk limit exceeded → BLOCK','Authority revoked → STOP','Execution not reconciled → never show a false SUCCESS']},
  {k:'status',title:'Where the project is now',lead:'Devnet first. Proof first. Mainnet is not open.',body:'The canonical development environment is real Solana Devnet test transactions. The latest durable full-suite still contained unresolved checks, so the public site must not imply Mainnet readiness. Mainnet execution also requires explicit human approval.',points:['TESTNET = Solana Devnet','Latest durable full-suite: 994 PASS / 61 FAIL / 1 SKIP','Readiness requires two consecutive clean verification passes with zero new P0/P1','Mainnet execution remains hard-locked until explicit human approval']}
 ]
 return <section className="project-details section-shell" id="learn-more" aria-labelledby="project-details-title"><div className="project-details__head" data-reveal="0" data-reveal-kind="title"><span className="eyebrow">{ru?'ПРОЕКТ БЕЗ МАРКЕТИНГОВОГО ШУМА':'THE PROJECT, WITHOUT THE NOISE'}</span><h2 id="project-details-title">{ru?'Понятно сначала.':'Understand it first.'}<br/><em>{ru?'Детали — по запросу.':'Details when you want them.'}</em></h2><p>{ru?'Короткие ответы остаются на поверхности. Откройте «Подробнее», когда нужен контекст — без перегрузки главной страницы.':'The short answer stays on the surface. Open “Learn more” when you want context, without turning the landing page into documentation.'}</p></div><div className="project-details__list">{items.map((item,i)=><details className="project-detail" key={item.k} data-reveal={String(Math.min(i*35,120))}><summary><span className="project-detail__summary"><strong>{item.title}</strong><small>{item.lead}</small></span><span className="project-detail__action"><span className="more">{ru?'Подробнее':'Learn more'}</span><span className="less">{ru?'Свернуть':'Close'}</span><i aria-hidden="true">+</i></span></summary><div className="project-detail__body"><p>{item.body}</p><ul>{item.points.map(p=><li key={p}>{p}</li>)}</ul></div></details>)}</div></section>
}
