"""Reproduce the reviewed first edition from archived public RPC responses. No network calls."""
import json
from pathlib import Path
p=Path(__file__).resolve().parents[1]/'public/radar'; evidence=p/'evidence'; (p/'observations').mkdir(exist_ok=True)
pro=json.loads((evidence/'provenance.json').read_text())
L=lambda en,ru:{'en':en,'ru':ru}
now='2026-09-17T02:27:05Z'
checked=pro['finishedAt'];event='2026-09-17T02:21:46Z'
records=[]
texts=[
 dict(id='finalized-but-failed',version=1,category=L('EXECUTION / 01','ИСПОЛНЕНИЕ / 01'),title=L('Finalized does not mean successful.','Финализировано — не значит успешно.'),summary=L('A finalized transaction carries an execution error—and a 5,001-lamport fee. Two different questions, one public record.','У финализированной транзакции есть ошибка исполнения и комиссия 5 001 лампорт. Два разных вопроса — одна публичная запись.'),facts=[
 L('At slot 447680207, the sampled transaction reports InstructionError at instruction index 6, with custom code 5000. The later status lookup still reports finalized and the same error.','В слоте 447680207 транзакция содержит InstructionError на инструкции с индексом 6, код программы — 5000. Последующая проверка статуса также показывает finalized и ту же ошибку.'),
 L('The metadata fee is 5,001 lamports. The fee-payer SOL balance decreases by exactly that amount in the recorded pre/post balances.','Комиссия в метаданных — 5 001 лампорт. В сохранённых балансах до и после операции SOL-баланс плательщика уменьшается ровно на эту сумму.'),
 L('All 11 token-balance entries present both before and after this transaction have unchanged raw amounts in the response.','У всех 11 записей токен-балансов, присутствующих до и после транзакции, исходные количества совпадают.')],
 interpretation=L('Finality and execution outcome are separate fields. This record supports a failed execution with a charged fee—not a completed buy. Reading a signature or finality label alone would miss that distinction.','Финальность и результат исполнения — разные поля. Эта запись подтверждает ошибку исполнения и списанную комиссию, а не завершённую покупку. Одной подписи или метки финальности недостаточно.'),
 unknowns=[L('We did not identify the fee payer or infer their strategy. Custom code 5000 is not interpreted as a universal Solana error.','Мы не устанавливали личность плательщика и его стратегию. Код 5000 не трактуется как универсальная ошибка Solana.'),L('Balance comparisons do not inspect every account-data change. This transaction contains a durable-nonce instruction; fee and nonce behavior are not evidence that absolutely all state remained untouched.','Сравнение балансов не проверяет все изменения данных аккаунтов. В транзакции есть инструкция durable nonce: нельзя утверждать, что вообще всё состояние осталось неизменным.')],
 note=L('Initial review of the signature list, transaction metadata and subsequent status response. All three checks were completed for this first edition.','Первичная проверка списка подписей, метаданных транзакции и последующего ответа о статусе. Все три проверки выполнены для первого выпуска.')),
 dict(id='success-without-token-movement',version=1,category=L('POSTCONDITIONS / 02','РЕЗУЛЬТАТ / 02'),title=L('A success flag is not a trade receipt.','Статус success — ещё не отчёт о сделке.'),summary=L('This successful call references 41 accounts. Its ten reported token balances do not change. A program outcome is not the same as a verified swap.','Успешный вызов ссылается на 41 аккаунт. Десять указанных токен-балансов не меняются. Успех программы — не подтверждение обмена.'),facts=[
 L('The transaction at slot 447680207 has meta.err = null and three top-level instructions. The subsequent status lookup is finalized, without an execution error.','У транзакции в слоте 447680207 meta.err = null и три инструкции верхнего уровня. Последующая проверка показывает finalized без ошибки исполнения.'),
 L('The response lists 41 message account keys and no recorded inner instructions. All ten matching pre/post token amounts are unchanged.','Ответ содержит 41 ключ аккаунта и не содержит записанных внутренних инструкций. У всех десяти сопоставленных записей токенов количества до и после совпадают.'),
 L('The fee is 5,002 lamports; the recorded fee-payer SOL delta is −5,002 lamports.','Комиссия — 5 002 лампорт; зафиксированное изменение SOL-баланса плательщика — −5 002 лампорт.')],
 interpretation=L('The record establishes that execution returned without an error. It does not establish that a purchase happened. Check the intended postconditions and the actual balance changes rather than treating every successful transaction as a trade.','Запись подтверждает исполнение без ошибки, но не доказывает покупку. Проверяйте ожидаемый результат и реальные изменения балансов, а не считайте любую успешную транзакцию сделкой.'),
 unknowns=[L('No conclusion is made about the program’s purpose, private off-chain activity or changes in account data not covered by token-balance fields.','Мы не делаем выводов о назначении программы, внецепочной активности или изменениях данных аккаунтов, не отражённых в токен-балансах.'),L('This one record is not a profitability assessment, a wallet ranking or a representative sample of Solana activity.','Одна запись — не оценка доходности, не рейтинг кошельков и не репрезентативная выборка активности Solana.')],
 note=L('Initial review compares error state, instruction counts, fee and matching token-balance entries in the archived RPC response.','Первичная проверка сопоставляет ошибку исполнения, количество инструкций, комиссию и токен-балансы в сохранённом ответе RPC.')),
 dict(id='gross-transfer-net-change',version=2,category=L('RECONCILIATION / 03','СВЕРКА / 03'),title=L('5.384 SOL moved. That is not the net result.','Переведено 5,384 SOL. Но это не итог.'),summary=L('One transaction contains wrapping, transfers and account closures. Following a single transfer hides the rest of the operation.','В одной транзакции — оборачивание SOL, переводы и закрытия аккаунта. Один перевод не описывает результат всей операции.'),facts=[
 L('The transaction at slot 447680207 reports no execution error and contains ten top-level instructions, including a System transfer of 5,384,061,455 lamports to a token account.','Транзакция в слоте 447680207 не содержит ошибки исполнения. Среди десяти инструкций верхнего уровня есть System-перевод 5 384 061 455 лампорт на токен-аккаунт.'),
 L('The same message contains syncNative and two closeAccount instructions. The recorded inner instructions include wrapped-SOL transfers in both directions.','В том же сообщении есть syncNative и две инструкции closeAccount. Среди записанных внутренних инструкций присутствуют переводы обёрнутого SOL в обе стороны.'),
 L('The later status response confirms finalized without an execution error. The balance reconciliation below is a separate editorial check of this same transaction.','Последующий ответ о статусе подтверждает finalized без ошибки исполнения. Сверка балансов ниже — отдельная редакционная проверка этой же транзакции.')],
 interpretation=L('A gross transfer is one step, not portfolio PnL. Account creation, wrapped SOL, returned funds, token balances and fees need to be considered together before describing an outcome.','Валовой перевод — лишь один шаг, не PnL портфеля. Создание аккаунта, обёрнутый SOL, возврат средств, токен-балансы и комиссия требуют совместного рассмотрения.'),
 unknowns=[L('No fiat prices or acquisition cost were verified. A SOL balance decrease alone is not labelled a loss; other assets also changed.','Цены в фиатной валюте и стоимость приобретения не проверялись. Снижение SOL-баланса не называем убытком: изменились и другие активы.'),L('This is an editorial study of a third-party transaction, not execution evidence for CopyPump or a recommendation to repeat it.','Это редакционный разбор чужой транзакции, не доказательство исполнения CopyPump и не рекомендация её повторять.')],
 note=L('The initial reading identifies a large transfer and surrounding instructions. The additional reconciliation was prepared within the first edition; it is not presented as a later market development.','Первичный разбор выделяет крупный перевод и окружающие инструкции. Дополнительная сверка подготовлена в первом выпуске; она не выдана за более позднее рыночное событие.'))
]
for i,c in enumerate(texts,1):
 raw=json.loads((evidence/f'transaction-{i}.json').read_text())['result'];sig=raw['transaction']['signatures'][0]
 sources=[{'id':'transaction','label':L('Archived RPC transaction response','Сохранённый ответ RPC: транзакция'),'url':f'/radar/evidence/transaction-{i}.json','checkedAt':pro['calls'][i]['receivedAt'],'sha256':pro['calls'][i]['sha256']},{'id':'status','label':L('Subsequent status lookup','Последующая проверка статуса'),'url':'/radar/evidence/follow-up-statuses.json','checkedAt':checked,'sha256':pro['calls'][-1]['sha256']},{'id':'explorer','label':L('Open transaction in Solana Explorer','Транзакция в Solana Explorer'),'url':f'https://explorer.solana.com/tx/{sig}?cluster=mainnet-beta','checkedAt':checked},{'id':'method','label':L('Collection method & source hashes','Метод отбора и контрольные суммы'),'url':'/radar/evidence/provenance.json','checkedAt':checked},{'id':'docs','label':L('Solana RPC response fields','Поля ответа Solana RPC'),'url':'https://solana.com/docs/rpc/json-structures','checkedAt':now}]
 rec={k:v for k,v in c.items() if k!='note'}
 rec.update(publishedAt=now,updatedAt=now,observedAt=event,lastCheckedAt=checked,cluster='mainnet-beta',signature=sig,followUps=1 if i==3 else 0,sources=sources,revisions=[{'version':1,'at':now,'kind':'initial','title':L('Initial evidence review','Первичная проверка источника'),'text':c['note'],'sourceIds':['transaction','status']}])
 if i==3:
  delta=raw['meta']['postBalances'][0]-raw['meta']['preBalances'][0];assert delta==-55897338
  before=next(x for x in raw['meta']['preTokenBalances'] if x['accountIndex']==3);after=next(x for x in raw['meta']['postTokenBalances'] if x['accountIndex']==3);diff=int(after['uiTokenAmount']['amount'])-int(before['uiTokenAmount']['amount']);assert diff==243974449436
  rec['revisions'].append({'version':2,'at':now,'kind':'addendum','title':L('Net balances, not one gross transfer','Итоговые балансы вместо одного перевода'),'text':L('Additional first-edition check: the fee-payer SOL balance changes by −55,897,338 lamports (−0.055897338 SOL), including the 5,601-lamport network fee. Token account index 3 increases by 243,974,449,436 raw units with 6 decimals. This is not a monetary PnL calculation; the token valuation and cost basis are unknown.','Дополнительная проверка первого выпуска: SOL-баланс плательщика меняется на −55 897 338 лампорт (−0,055897338 SOL), включая сетевую комиссию 5 601 лампорт. Баланс токен-аккаунта с индексом 3 увеличивается на 243 974 449 436 исходных единиц при 6 знаках после запятой. Это не расчёт денежного PnL: оценка токена и стоимость приобретения неизвестны.'),'sourceIds':['transaction','status']})
 (p/'observations'/f'{c["id"]}.json').write_text(json.dumps(rec,ensure_ascii=False,indent=2)+'\n')
 records.append({k:rec[k] for k in ['id','version','publishedAt','updatedAt','observedAt','lastCheckedAt','cluster','title','summary','category','followUps']})
(p/'index.json').write_text(json.dumps({'schemaVersion':1,'edition':'01','publishedAt':now,'items':[records[2],records[0],records[1]]},ensure_ascii=False,indent=2)+'\n')
